spring.application.name=JobPortal

server.port=${PORT:8080}
server.servlet.context-path=/api

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jobportal}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:@ranjit0710}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET:8f4c2d9e1b7a6c5f8e2d1a9b4c7e6f5a8d3c1b7e9f2a4c6d8e1f3b5a7c9d2e4}
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

# CORS (include 5174 when Vite falls back if 5173 is busy)
app.cors.allowed-origins=https://job-frontend-clyj.vercel.app